### ISSUE TITLE
Android 4.0 issue

### ISSUE THREAD

**Issue by ironsidevsquincy** [getify/native-promise-only#38] opened 2014-11-05 16:56 UTC
Specifically this, might occur on other clients, but Android 4 doesn't play well when `Object.defineProperty` is used to set the `prototype`, i.e. the `__NPO__` isn't being set for these clients

Solution for now was to replace https://github.com/getify/native-promise-only/blob/master/lib/npo.src.js#L283 with

```Promise.prototype = PromisePrototype;```

**Comment by mzgol** [comment] 2015-03-23 17:28
jQuery is now using NPO to test compliance of its Deferreds against the Promises/A+ tests and this issue is causing `jQuery.when` tests to fail. See http://swarm.jquery.org/result/99082

What else is needed to get #38 merged?

**Comment by getify** [comment] 2015-03-24 00:53
Sorry that this got hung up for so long on #41. We were discussing possible file reorg and tests and such, and I think we missed the forest for the trees. So I've just landed a fix only for the Android thing (hopefully!).

**Comment by mzgol** [comment] 2015-03-26 14:08
@getify Thanks! It turns out jQuery test errors are caused by another issue, see #43.

**Comment by getify** [comment] 2015-03-26 16:24
Actually, I didn't fix this issue correctly after all. :(

**Comment by getify** [comment] 2015-03-26 16:42
Man, this android4 browser behavior is insane. If you use `Object.defineProperty`, it actually does change the descriptor, but not the underlying function value. Then, even better, subsequently if you try to set it with normal `=` assignment, **THAT** assignment silently fails. `=` assignment only works if you haven't previously done the `Object.defineProperty`.

**Closed** 2015-03-26 16:57 UTC

**Comment by getify** [comment] 2015-03-26 17:14
For posterity sake, the observation I made was that the `builtInProp(..)` usage before was actually setting the same sort of descriptor (`writable:true, enumerable:false, configurable:false`) as is already true of function prototypes (per spec)... so the normal `=` assignment is shorter, accomplishes the same thing, **and** most importantly doesn't trigger this android4 stupidity.
